# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  username: postgres
  password: wanjiri22
  encoding: unicode
  database:  
  pool: 5


test:
  adapter: postgresql
  encoding: unicode
  database: HpgApp_test
  pool: 5
  username: #hodaritoure
  password:

production:
  adapter: postgresql
  database: HgpApp_production
  pool: 5
  timeout: 5000
